//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ses2._1.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user17Entities : DbContext
    {
        public user17Entities()
            : base("name=user17Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<avtobus> avtobus { get; set; }
        public DbSet<marchrut> marchrut { get; set; }
        public DbSet<poezdki> poezdki { get; set; }
        public DbSet<voditela> voditela { get; set; }
    }
}
