//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ses2._1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class voditela
    {
        public voditela()
        {
            this.avtobus = new HashSet<avtobus>();
        }
    
        public int id_voditela { get; set; }
        public string FIO { get; set; }
        public string addres { get; set; }
        public string number { get; set; }
    
        public virtual ICollection<avtobus> avtobus { get; set; }
    }
}
